# Site of Antonio Vanegas P. (@hpsaturn)
title:              Hpsaturn
bio:                '"Talk is cheap. Show me the code"'
description:        "Mobile applications specialist, open culture enthusiast, software freedom activist."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
photo:              'assets/img/about00.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url: "https://hpsaturn.com" # the base hostname & protocol for your site, e.g. http://example.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  analytics: UA-158722471-1
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            hpsaturn
#facebook:           
github-url:         hpsaturn
stackoverflow:      471690/hpsaturn
linkedin:           hpsaturn
#xing:              username
instagram:          hpsaturn
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:         hpsaturn
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
hackaday:           hpsaturn

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
